version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11rc2

    environment:
      TEST_REPORT_PATH: /tmp/test-results

    steps:
      - checkout
      - run: make setup
      - run: make dist
      - run: make lint
      - run: make test
      - store_artifacts:
          path: target
          destination: target
      - store_test_results:
          path: target/test-results
