http_addr=":8080"
extra-js=""
base-url="http://127.0.0.1:8080"
https_addr=":8085"
newrelic_app-name="Evepraisal"
db_path="db/"
sso-verify-url="https://login.eveonline.com/oauth/verify"
newrelic_license-key=""
backup_path="db/backups/"
letsencrypt_email=""
esi_baseurl="https://esi.evetech.net/latest"
sso-authorize-url="https://login.eveonline.com/oauth/authorize"
https_domain-whitelist="evepraisal.com"
ad-block=""
management_addr="127.0.0.1:8090"
sso-token-url="https://login.eveonline.com/oauth/token"
http_redirect=false

